//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tweet()
        {
            this.Mentions = new HashSet<Mention>();
            this.TweetHashtags = new HashSet<TweetHashtag>();
        }
    
        public long TweetId { get; set; }
        public long UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string TweetText { get; set; }
        public bool IsQuoteStatus { get; set; }
        public bool IsRetweet { get; set; }
        public Nullable<long> ReplyToTweetId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mention> Mentions { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TweetHashtag> TweetHashtags { get; set; }
    }
}
